import { fileURLToPath } from "node:url";
import { defineConfig } from "vitest/config";

export default defineConfig({
  resolve: {
    alias: {
      // Mirrors tsconfig.json `paths` so `@/generated/prisma/client` resolves in tests.
      "@": fileURLToPath(new URL("./src", import.meta.url)),
    },
  },
  test: {
    environment: "node",
    globals: true,
    include: ["src/**/*.test.ts", "tests/**/*.test.ts"],
    exclude: ["tests/db/**"],
    setupFiles: ["tests/helpers/setup-env.ts"],
    coverage: {
      provider: "v8",
      include: [
        "src/adapters/vps.adapter.ts",
        "src/routes/webhooks.ts",
        "src/jobs/webhookProcessor.inngest.ts",
        "src/lib/validateEnv.ts",
        "src/lib/encryption.ts",
        "src/lib/money.ts",
        "src/lib/billing.ts",
        "src/lib/dunning.ts",
        "src/lib/status-maps.ts",
        "src/lib/mask.ts",
        "src/lib/webhook-verify.ts",
        "src/lib/webhook-sign.ts",
        "src/routes/auth.ts",
        "src/routes/users.ts",
        "src/routes/tenant.ts",
        "src/routes/apiKeys.ts",
        "src/routes/paymentLinks.ts",
        "src/routes/paymentIntents.ts",
        "src/routes/transactions.ts",
        "src/routes/refunds.ts",
        "src/routes/subscriptions.ts",
        "src/routes/installmentPlans.ts",
        "src/routes/installmentAgreements.ts",
        "src/routes/admin.ts",
        "src/routes/exports.ts",
        "src/routes/dashboard.ts",
        "src/routes/providerConfig.ts",
        "src/routes/ledger.ts",
        "src/lib/ledger.ts",
        "src/lib/fees.ts",
        "src/lib/settlement-policy.ts",
        "src/lib/settlement-presets.ts",
        "src/routes/fee-schedules.ts",
        "src/routes/settlement-policies.ts",
      ],
      thresholds: {
        // Pure money/billing/encryption/status-maps helpers — 100% line coverage
        // (per the demo-seed + test plan). mask/webhook-verify are equally pure
        // and reach 100% for free.
        "src/lib/money.ts": { lines: 100 },
        "src/lib/billing.ts": { lines: 100 },
        "src/lib/encryption.ts": { lines: 100 },
        "src/lib/status-maps.ts": { lines: 100 },
        "src/lib/mask.ts": { lines: 100 },
        "src/lib/webhook-verify.ts": { lines: 100 },
        "src/lib/webhook-sign.ts": { lines: 100 },
        "src/lib/ledger.ts": { lines: 100 },
        "src/lib/fees.ts": { lines: 100 },
        "src/lib/settlement-policy.ts": { lines: 100 },
        "src/lib/settlement-presets.ts": { lines: 100 },
        "src/lib/validateEnv.ts": { lines: 100 },
        // Calibrated from measured baselines (a small buffer below each
        // measured % so coverage stays green while the suites grow).
        "src/lib/dunning.ts": { lines: 25 },
        "src/adapters/vps.adapter.ts": { lines: 20 },
        "src/routes/webhooks.ts": { lines: 60 },
        "src/routes/apiKeys.ts": { lines: 95 },
        "src/routes/auth.ts": { lines: 80 },
        "src/routes/dashboard.ts": { lines: 95 },
        "src/routes/exports.ts": { lines: 85 },
        "src/routes/installmentAgreements.ts": { lines: 80 },
        "src/routes/installmentPlans.ts": { lines: 90 },
        "src/routes/paymentIntents.ts": { lines: 65 },
        "src/routes/paymentLinks.ts": { lines: 90 },
        "src/routes/providerConfig.ts": { lines: 75 },
        "src/routes/refunds.ts": { lines: 80 },
        "src/routes/subscriptions.ts": { lines: 85 },
        "src/routes/tenant.ts": { lines: 85 },
        "src/routes/transactions.ts": { lines: 80 },
        "src/routes/users.ts": { lines: 75 },
        "src/routes/admin.ts": { lines: 45 },
        "src/routes/ledger.ts": { lines: 90 },
        "src/routes/fee-schedules.ts": { lines: 90 },
        "src/routes/settlement-policies.ts": { lines: 90 },
      },
      reporter: ["text", "lcov"],
    },
  },
});
